allowBuilds:
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@vitest/coverage-v8@4.1.11'
  - '@vitest/expect@4.1.11'
  - '@vitest/mocker@4.1.11'
  - '@vitest/pretty-format@4.1.11'
  - '@vitest/runner@4.1.11'
  - '@vitest/snapshot@4.1.11'
  - '@vitest/spy@4.1.11'
  - '@vitest/utils@4.1.11'
  - fastify@5.12.1
  - vitest@4.1.11
